package com.adhar.kit.maven.generator;

import com.squareup.javapoet.*;
import org.apache.maven.plugin.logging.Log;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;

/**
 * Generator for REST controller classes.
 *
 * <p>Generates Spring REST controllers with CRUD endpoints,
 * optional OpenAPI annotations, and standard response handling.</p>
 *
 * @author Adhar Platform Team
 * @since 1.0.0
 */
public class ControllerGenerator {
    private final String basePackage;
    private final String entityName;
    private final File outputDirectory;
    private final boolean withOpenApi;
    private final Log log;

    public ControllerGenerator(String basePackage, String entityName, File outputDirectory,
                              boolean withOpenApi, Log log) {
        this.basePackage = basePackage;
        this.entityName = entityName;
        this.outputDirectory = outputDirectory;
        this.withOpenApi = withOpenApi;
        this.log = log;
    }

    /**
     * Generates a REST controller with CRUD endpoints.
     */
    public void generate() throws IOException {
        log.info("Generating REST controller for: " + entityName);

        String className = entityName + "Controller";
        String packageName = basePackage + ".controller";
        String entityLower = decapitalize(entityName);

        ClassName serviceType = ClassName.get(basePackage + ".service", entityName + "Service");
        ClassName createDto = ClassName.get(basePackage + ".dto", entityName + "CreateDto");
        ClassName updateDto = ClassName.get(basePackage + ".dto", entityName + "UpdateDto");
        ClassName responseDto = ClassName.get(basePackage + ".dto", entityName + "ResponseDto");
        ClassName responseEntity = ClassName.get("org.springframework.http", "ResponseEntity");
        ClassName pageable = ClassName.get("org.springframework.data.domain", "Pageable");
        ClassName page = ClassName.get("org.springframework.data.domain", "Page");

        TypeSpec.Builder controllerBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("REST controller for $L operations.\n", entityName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RestController"))
                .addAnnotation(AnnotationSpec.builder(
                                ClassName.get("org.springframework.web.bind.annotation", "RequestMapping"))
                        .addMember("value", "$S", "/api/v1/" + entityLower + "s")
                        .build())
                .addAnnotation(ClassName.get("lombok", "RequiredArgsConstructor"))
                .addAnnotation(ClassName.get("lombok.extern.slf4j", "Slf4j"));

        if (withOpenApi) {
            controllerBuilder.addAnnotation(AnnotationSpec.builder(
                            ClassName.get("io.swagger.v3.oas.annotations.tags", "Tag"))
                    .addMember("name", "$S", entityName + "s")
                    .addMember("description", "$S", "Operations for " + entityName + " management")
                    .build());
        }

        // Service field
        controllerBuilder.addField(FieldSpec.builder(serviceType, entityLower + "Service",
                Modifier.PRIVATE, Modifier.FINAL).build());

        // CREATE endpoint
        MethodSpec.Builder createMethod = MethodSpec.methodBuilder("create")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(
                                ClassName.get("org.springframework.web.bind.annotation", "PostMapping"))
                        .build())
                .addParameter(ParameterSpec.builder(createDto, "dto")
                        .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RequestBody"))
                        .addAnnotation(ClassName.get("jakarta.validation", "Valid"))
                        .build())
                .returns(ParameterizedTypeName.get(responseEntity, responseDto))
                .addStatement("log.info($S, dto)", "Creating " + entityName + ": {}")
                .addStatement("$T result = $NService.create(dto)", responseDto, entityLower)
                .addStatement("return $T.status($T.CREATED).body(result)",
                        responseEntity,
                        ClassName.get("org.springframework.http", "HttpStatus"));

        if (withOpenApi) {
            createMethod.addAnnotation(AnnotationSpec.builder(
                            ClassName.get("io.swagger.v3.oas.annotations", "Operation"))
                    .addMember("summary", "$S", "Create a new " + entityName)
                    .addMember("description", "$S", "Creates a new " + entityName + " resource")
                    .build());
        }

        controllerBuilder.addMethod(createMethod.build());

        // GET BY ID endpoint
        MethodSpec.Builder getByIdMethod = MethodSpec.methodBuilder("getById")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(
                                ClassName.get("org.springframework.web.bind.annotation", "GetMapping"))
                        .addMember("value", "$S", "/{id}")
                        .build())
                .addParameter(ParameterSpec.builder(Long.class, "id")
                        .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                        .build())
                .returns(ParameterizedTypeName.get(responseEntity, responseDto))
                .addStatement("log.info($S, id)", "Fetching " + entityName + " with id: {}")
                .addStatement("$T result = $NService.findById(id)", responseDto, entityLower)
                .addStatement("return $T.ok(result)", responseEntity);

        if (withOpenApi) {
            getByIdMethod.addAnnotation(AnnotationSpec.builder(
                            ClassName.get("io.swagger.v3.oas.annotations", "Operation"))
                    .addMember("summary", "$S", "Get " + entityName + " by ID")
                    .build());
        }

        controllerBuilder.addMethod(getByIdMethod.build());

        // GET ALL endpoint
        MethodSpec.Builder getAllMethod = MethodSpec.methodBuilder("getAll")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(
                                ClassName.get("org.springframework.web.bind.annotation", "GetMapping"))
                        .build())
                .addParameter(pageable, "pageable")
                .returns(ParameterizedTypeName.get(responseEntity,
                        ParameterizedTypeName.get(page, responseDto)))
                .addStatement("log.info($S)", "Fetching all " + entityName + "s")
                .addStatement("$T<$T> result = $NService.findAll(pageable)",
                        page, responseDto, entityLower)
                .addStatement("return $T.ok(result)", responseEntity);

        if (withOpenApi) {
            getAllMethod.addAnnotation(AnnotationSpec.builder(
                            ClassName.get("io.swagger.v3.oas.annotations", "Operation"))
                    .addMember("summary", "$S", "Get all " + entityName + "s with pagination")
                    .build());
        }

        controllerBuilder.addMethod(getAllMethod.build());

        // UPDATE endpoint
        MethodSpec.Builder updateMethod = MethodSpec.methodBuilder("update")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(
                                ClassName.get("org.springframework.web.bind.annotation", "PutMapping"))
                        .addMember("value", "$S", "/{id}")
                        .build())
                .addParameter(ParameterSpec.builder(Long.class, "id")
                        .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                        .build())
                .addParameter(ParameterSpec.builder(updateDto, "dto")
                        .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RequestBody"))
                        .addAnnotation(ClassName.get("jakarta.validation", "Valid"))
                        .build())
                .returns(ParameterizedTypeName.get(responseEntity, responseDto))
                .addStatement("log.info($S, id)", "Updating " + entityName + " with id: {}")
                .addStatement("$T result = $NService.update(id, dto)", responseDto, entityLower)
                .addStatement("return $T.ok(result)", responseEntity);

        if (withOpenApi) {
            updateMethod.addAnnotation(AnnotationSpec.builder(
                            ClassName.get("io.swagger.v3.oas.annotations", "Operation"))
                    .addMember("summary", "$S", "Update an existing " + entityName)
                    .build());
        }

        controllerBuilder.addMethod(updateMethod.build());

        // DELETE endpoint
        MethodSpec.Builder deleteMethod = MethodSpec.methodBuilder("delete")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(
                                ClassName.get("org.springframework.web.bind.annotation", "DeleteMapping"))
                        .addMember("value", "$S", "/{id}")
                        .build())
                .addParameter(ParameterSpec.builder(Long.class, "id")
                        .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                        .build())
                .returns(ParameterizedTypeName.get(responseEntity, ClassName.get("java.lang", "Void")))
                .addStatement("log.info($S, id)", "Deleting " + entityName + " with id: {}")
                .addStatement("$NService.delete(id)", entityLower)
                .addStatement("return $T.noContent().build()", responseEntity);

        if (withOpenApi) {
            deleteMethod.addAnnotation(AnnotationSpec.builder(
                            ClassName.get("io.swagger.v3.oas.annotations", "Operation"))
                    .addMember("summary", "$S", "Delete " + entityName + " by ID")
                    .build());
        }

        controllerBuilder.addMethod(deleteMethod.build());

        // Write the file
        JavaFile javaFile = JavaFile.builder(packageName, controllerBuilder.build())
                .addFileComment("Generated by Adhar Kit Maven Plugin")
                .indent("    ")
                .build();

        javaFile.writeTo(outputDirectory);
        log.info("Generated controller: " + className);
    }

    private String decapitalize(String name) {
        return Character.toLowerCase(name.charAt(0)) + name.substring(1);
    }
}
