package com.adhar.kit.maven.generator;

import com.squareup.javapoet.*;
import org.apache.maven.plugin.logging.Log;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;

/**
 * Generator for DTO (Data Transfer Object) classes.
 *
 * <p>Generates Create, Update, and Response DTOs with validation annotations
 * and optional Lombok support.</p>
 *
 * @author Adhar Platform Team
 * @since 1.0.0
 */
public class DtoGenerator {
    private final String basePackage;
    private final String entityName;
    private final File outputDirectory;
    private final boolean useLombok;
    private final Log log;

    public DtoGenerator(String basePackage, String entityName, File outputDirectory,
                       boolean useLombok, Log log) {
        this.basePackage = basePackage;
        this.entityName = entityName;
        this.outputDirectory = outputDirectory;
        this.useLombok = useLombok;
        this.log = log;
    }

    /**
     * Generates CreateDto, UpdateDto, and ResponseDto for the entity.
     */
    public void generate() throws IOException {
        log.info("Generating DTOs for: " + entityName);
        generateCreateDto();
        generateUpdateDto();
        generateResponseDto();
        log.info("Generated DTOs for: " + entityName);
    }

    private void generateCreateDto() throws IOException {
        String className = entityName + "CreateDto";
        String packageName = basePackage + ".dto";

        TypeSpec.Builder builder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("DTO for creating a new $L.\n", entityName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n");

        if (useLombok) {
            builder.addAnnotation(ClassName.get("lombok", "Data"))
                    .addAnnotation(ClassName.get("lombok", "Builder"))
                    .addAnnotation(ClassName.get("lombok", "NoArgsConstructor"))
                    .addAnnotation(ClassName.get("lombok", "AllArgsConstructor"));
        }

        // Add a sample name field with validation
        builder.addField(FieldSpec.builder(String.class, "name", Modifier.PRIVATE)
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.validation.constraints", "NotBlank"))
                        .addMember("message", "$S", "Name is required")
                        .build())
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.validation.constraints", "Size"))
                        .addMember("max", "$L", 255)
                        .addMember("message", "$S", "Name must not exceed 255 characters")
                        .build())
                .build());

        builder.addField(FieldSpec.builder(String.class, "description", Modifier.PRIVATE)
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.validation.constraints", "Size"))
                        .addMember("max", "$L", 1000)
                        .addMember("message", "$S", "Description must not exceed 1000 characters")
                        .build())
                .build());

        if (!useLombok) {
            addGettersAndSetters(builder, "name", String.class);
            addGettersAndSetters(builder, "description", String.class);
        }

        writeJavaFile(packageName, builder.build());
        log.info("Generated: " + className);
    }

    private void generateUpdateDto() throws IOException {
        String className = entityName + "UpdateDto";
        String packageName = basePackage + ".dto";

        TypeSpec.Builder builder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("DTO for updating an existing $L.\n", entityName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n");

        if (useLombok) {
            builder.addAnnotation(ClassName.get("lombok", "Data"))
                    .addAnnotation(ClassName.get("lombok", "Builder"))
                    .addAnnotation(ClassName.get("lombok", "NoArgsConstructor"))
                    .addAnnotation(ClassName.get("lombok", "AllArgsConstructor"));
        }

        builder.addField(FieldSpec.builder(String.class, "name", Modifier.PRIVATE)
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.validation.constraints", "Size"))
                        .addMember("max", "$L", 255)
                        .addMember("message", "$S", "Name must not exceed 255 characters")
                        .build())
                .build());

        builder.addField(FieldSpec.builder(String.class, "description", Modifier.PRIVATE)
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.validation.constraints", "Size"))
                        .addMember("max", "$L", 1000)
                        .addMember("message", "$S", "Description must not exceed 1000 characters")
                        .build())
                .build());

        if (!useLombok) {
            addGettersAndSetters(builder, "name", String.class);
            addGettersAndSetters(builder, "description", String.class);
        }

        writeJavaFile(packageName, builder.build());
        log.info("Generated: " + className);
    }

    private void generateResponseDto() throws IOException {
        String className = entityName + "ResponseDto";
        String packageName = basePackage + ".dto";

        TypeSpec.Builder builder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Response DTO for $L.\n", entityName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n");

        if (useLombok) {
            builder.addAnnotation(ClassName.get("lombok", "Data"))
                    .addAnnotation(ClassName.get("lombok", "Builder"))
                    .addAnnotation(ClassName.get("lombok", "NoArgsConstructor"))
                    .addAnnotation(ClassName.get("lombok", "AllArgsConstructor"));
        }

        builder.addField(FieldSpec.builder(Long.class, "id", Modifier.PRIVATE).build());
        builder.addField(FieldSpec.builder(String.class, "name", Modifier.PRIVATE).build());
        builder.addField(FieldSpec.builder(String.class, "description", Modifier.PRIVATE).build());
        builder.addField(FieldSpec.builder(ClassName.get("java.time", "LocalDateTime"),
                "createdAt", Modifier.PRIVATE).build());
        builder.addField(FieldSpec.builder(ClassName.get("java.time", "LocalDateTime"),
                "updatedAt", Modifier.PRIVATE).build());

        if (!useLombok) {
            addGettersAndSetters(builder, "id", Long.class);
            addGettersAndSetters(builder, "name", String.class);
            addGettersAndSetters(builder, "description", String.class);
            // For LocalDateTime fields, use TypeName approach
            addGetterAndSetter(builder, "createdAt", ClassName.get("java.time", "LocalDateTime"));
            addGetterAndSetter(builder, "updatedAt", ClassName.get("java.time", "LocalDateTime"));
        }

        writeJavaFile(packageName, builder.build());
        log.info("Generated: " + className);
    }

    private void addGettersAndSetters(TypeSpec.Builder builder, String fieldName, Class<?> type) {
        addGetterAndSetter(builder, fieldName, TypeName.get(type));
    }

    private void addGetterAndSetter(TypeSpec.Builder builder, String fieldName, TypeName type) {
        String capitalized = Character.toUpperCase(fieldName.charAt(0)) + fieldName.substring(1);

        builder.addMethod(MethodSpec.methodBuilder("get" + capitalized)
                .addModifiers(Modifier.PUBLIC)
                .returns(type)
                .addStatement("return this.$N", fieldName)
                .build());

        builder.addMethod(MethodSpec.methodBuilder("set" + capitalized)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(type, fieldName)
                .returns(TypeName.VOID)
                .addStatement("this.$N = $N", fieldName, fieldName)
                .build());
    }

    private void writeJavaFile(String packageName, TypeSpec typeSpec) throws IOException {
        JavaFile javaFile = JavaFile.builder(packageName, typeSpec)
                .addFileComment("Generated by Adhar Kit Maven Plugin")
                .indent("    ")
                .build();
        javaFile.writeTo(outputDirectory);
    }
}
