package com.adhar.kit.maven.generator;

import com.squareup.javapoet.*;
import org.apache.maven.plugin.logging.Log;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;

/**
 * Generator for JPA entity classes.
 *
 * <p>Generates enterprise-ready entity classes with:</p>
 * <ul>
 *   <li>{@code @Entity} / {@code @Table} mapping</li>
 *   <li>Auto-generated identifier ({@code @Id} / {@code @GeneratedValue})</li>
 *   <li>Auditing fields (createdAt / updatedAt) via {@code @EntityListeners}</li>
 *   <li>A couple of sample business fields matching the generated DTOs</li>
 *   <li>Getters/setters or Lombok annotations, matching the module's convention</li>
 * </ul>
 *
 * @author Adhar Platform Team
 * @since 1.0.0
 */
public class EntityGenerator {

    private final String basePackage;
    private final String entityName;
    private final File outputDirectory;
    private final boolean useLombok;
    private final String tableName;
    private final Log log;

    public EntityGenerator(String basePackage, String entityName, File outputDirectory,
                            boolean useLombok, String tableName, Log log) {
        this.basePackage = basePackage;
        this.entityName = entityName;
        this.outputDirectory = outputDirectory;
        this.useLombok = useLombok;
        this.tableName = (tableName == null || tableName.isBlank())
                ? defaultTableName(entityName)
                : tableName;
        this.log = log;
    }

    /**
     * Generates the JPA entity class.
     */
    public void generate() throws IOException {
        log.info("Generating entity for: " + entityName);

        String packageName = basePackage + ".entity";

        TypeSpec.Builder entityBuilder = TypeSpec.classBuilder(entityName)
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Entity representing a $L.\n", entityName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addSuperinterface(ClassName.get("java.io", "Serializable"))
                .addAnnotation(ClassName.get("jakarta.persistence", "Entity"))
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "Table"))
                        .addMember("name", "$S", tableName)
                        .build())
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "EntityListeners"))
                        .addMember("value", "$T.class",
                                ClassName.get("org.springframework.data.jpa.domain.support", "AuditingEntityListener"))
                        .build());

        if (useLombok) {
            entityBuilder.addAnnotation(ClassName.get("lombok", "Getter"))
                    .addAnnotation(ClassName.get("lombok", "Setter"))
                    .addAnnotation(ClassName.get("lombok", "NoArgsConstructor"))
                    .addAnnotation(ClassName.get("lombok", "AllArgsConstructor"))
                    .addAnnotation(AnnotationSpec.builder(ClassName.get("lombok", "Builder")).build());
        }

        // Identifier field
        FieldSpec idField = FieldSpec.builder(ClassName.get(Long.class), "id", Modifier.PRIVATE)
                .addAnnotation(ClassName.get("jakarta.persistence", "Id"))
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "GeneratedValue"))
                        .addMember("strategy", "$T.$L",
                                ClassName.get("jakarta.persistence", "GenerationType"), "IDENTITY")
                        .build())
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "Column"))
                        .addMember("name", "$S", "id")
                        .addMember("updatable", "$L", false)
                        .addMember("nullable", "$L", false)
                        .build())
                .build();
        entityBuilder.addField(idField);

        // Sample business fields, matching the fields produced by DtoGenerator.
        entityBuilder.addField(FieldSpec.builder(String.class, "name", Modifier.PRIVATE)
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "Column"))
                        .addMember("name", "$S", "name")
                        .addMember("nullable", "$L", false)
                        .addMember("length", "$L", 255)
                        .build())
                .build());

        entityBuilder.addField(FieldSpec.builder(String.class, "description", Modifier.PRIVATE)
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "Column"))
                        .addMember("name", "$S", "description")
                        .addMember("length", "$L", 1000)
                        .build())
                .build());

        // Audit fields
        ClassName localDateTime = ClassName.get("java.time", "LocalDateTime");

        entityBuilder.addField(FieldSpec.builder(localDateTime, "createdAt", Modifier.PRIVATE)
                .addAnnotation(ClassName.get("org.springframework.data.annotation", "CreatedDate"))
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "Column"))
                        .addMember("name", "$S", "created_at")
                        .addMember("updatable", "$L", false)
                        .addMember("nullable", "$L", false)
                        .build())
                .build());

        entityBuilder.addField(FieldSpec.builder(localDateTime, "updatedAt", Modifier.PRIVATE)
                .addAnnotation(ClassName.get("org.springframework.data.annotation", "LastModifiedDate"))
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "Column"))
                        .addMember("name", "$S", "updated_at")
                        .build())
                .build());

        entityBuilder.addField(FieldSpec.builder(ClassName.get(Long.class), "version", Modifier.PRIVATE)
                .addAnnotation(ClassName.get("jakarta.persistence", "Version"))
                .addAnnotation(AnnotationSpec.builder(ClassName.get("jakarta.persistence", "Column"))
                        .addMember("name", "$S", "version")
                        .build())
                .build());

        if (!useLombok) {
            addGetterAndSetter(entityBuilder, "id", ClassName.get(Long.class));
            addGetterAndSetter(entityBuilder, "name", ClassName.get(String.class));
            addGetterAndSetter(entityBuilder, "description", ClassName.get(String.class));
            addGetterAndSetter(entityBuilder, "createdAt", localDateTime);
            addGetterAndSetter(entityBuilder, "updatedAt", localDateTime);
            addGetterAndSetter(entityBuilder, "version", ClassName.get(Long.class));

            // No-args constructor, matching JPA's requirement for a default constructor.
            entityBuilder.addMethod(MethodSpec.constructorBuilder()
                    .addModifiers(Modifier.PUBLIC)
                    .build());
        }

        // equals()/hashCode() based on identifier, following JPA entity best practice.
        entityBuilder.addMethod(MethodSpec.methodBuilder("equals")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.BOOLEAN)
                .addParameter(Object.class, "o")
                .beginControlFlow("if (this == o)")
                .addStatement("return true")
                .endControlFlow()
                .beginControlFlow("if (!(o instanceof $L that))", entityName)
                .addStatement("return false")
                .endControlFlow()
                .addStatement("return id != null && id.equals(that.id)")
                .build());

        entityBuilder.addMethod(MethodSpec.methodBuilder("hashCode")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.INT)
                .addStatement("return getClass().hashCode()")
                .build());

        JavaFile javaFile = JavaFile.builder(packageName, entityBuilder.build())
                .addFileComment("Generated by Adhar Kit Maven Plugin")
                .indent("    ")
                .build();

        javaFile.writeTo(outputDirectory);
        log.info("Generated entity: " + entityName + " (table: " + tableName + ")");
    }

    private void addGetterAndSetter(TypeSpec.Builder builder, String fieldName, TypeName type) {
        String capitalized = Character.toUpperCase(fieldName.charAt(0)) + fieldName.substring(1);

        builder.addMethod(MethodSpec.methodBuilder("get" + capitalized)
                .addModifiers(Modifier.PUBLIC)
                .returns(type)
                .addStatement("return this.$N", fieldName)
                .build());

        builder.addMethod(MethodSpec.methodBuilder("set" + capitalized)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(type, fieldName)
                .returns(TypeName.VOID)
                .addStatement("this.$N = $N", fieldName, fieldName)
                .build());
    }

    /**
     * Derives a reasonable snake_case, pluralized table name from the entity name,
     * e.g. {@code OrderItem -> order_items}.
     */
    static String defaultTableName(String name) {
        StringBuilder snake = new StringBuilder();
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            if (Character.isUpperCase(c)) {
                if (i > 0) {
                    snake.append('_');
                }
                snake.append(Character.toLowerCase(c));
            } else {
                snake.append(c);
            }
        }
        String base = snake.toString();
        if (base.endsWith("y") && !base.isEmpty() && !isVowel(base.charAt(base.length() - 2))) {
            return base.substring(0, base.length() - 1) + "ies";
        }
        if (base.endsWith("s") || base.endsWith("x") || base.endsWith("ch") || base.endsWith("sh")) {
            return base + "es";
        }
        return base + "s";
    }

    private static boolean isVowel(char c) {
        return "aeiou".indexOf(Character.toLowerCase(c)) >= 0;
    }
}
