package com.adhar.kit.maven.generator;

import com.squareup.javapoet.*;
import org.apache.maven.plugin.logging.Log;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;

/**
 * Generator for JUnit 5 integration test skeletons.
 *
 * <p>Produces a Spring Boot integration test skeleton for the generated service
 * and another for the generated REST controller, wired against the standard
 * generated package layout ({@code <basePackage>.service} / {@code .controller}).
 * The generated tests compile but only contain {@code @Test} method stubs marked
 * with {@code TODO} - they are a starting point, not a finished test suite.</p>
 *
 * @author Adhar Platform Team
 * @since 1.0.0
 */
public class IntegrationTestGenerator {

    private final String basePackage;
    private final String entityName;
    private final File outputDirectory;
    private final Log log;

    public IntegrationTestGenerator(String basePackage, String entityName, File outputDirectory, Log log) {
        this.basePackage = basePackage;
        this.entityName = entityName;
        this.outputDirectory = outputDirectory;
        this.log = log;
    }

    /**
     * Generates the service and controller integration test skeletons.
     */
    public void generate() throws IOException {
        generateServiceIntegrationTest();
        generateControllerIntegrationTest();
        log.info("Generated integration tests for: " + entityName);
    }

    private void generateServiceIntegrationTest() throws IOException {
        String className = entityName + "ServiceIntegrationTest";
        String packageName = basePackage + ".service";
        String entityLower = decapitalize(entityName);

        ClassName serviceType = ClassName.get(basePackage + ".service", entityName + "Service");
        ClassName createDto = ClassName.get(basePackage + ".dto", entityName + "CreateDto");
        ClassName responseDto = ClassName.get(basePackage + ".dto", entityName + "ResponseDto");
        ClassName springBootTest = ClassName.get("org.springframework.boot.test.context", "SpringBootTest");
        ClassName autowired = ClassName.get("org.springframework.beans.factory.annotation", "Autowired");
        ClassName test = ClassName.get("org.junit.jupiter.api", "Test");
        ClassName assertions = ClassName.get("org.assertj.core.api", "Assertions");

        TypeSpec.Builder testBuilder = TypeSpec.classBuilder(className)
                .addJavadoc("Integration test skeleton for $L.\n", entityName + "Service")
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addAnnotation(springBootTest)
                .addField(FieldSpec.builder(serviceType, entityLower + "Service", Modifier.PRIVATE)
                        .addAnnotation(autowired)
                        .build());

        testBuilder.addMethod(MethodSpec.methodBuilder("createsAnd" + entityName + "IsFindable")
                .addAnnotation(test)
                .addModifiers(Modifier.PUBLIC)
                .addStatement("$T dto = new $T()", createDto, createDto)
                .addStatement("$T created = $NService.create(dto)", responseDto, entityLower)
                .addStatement("$T.assertThat(created).isNotNull()", assertions)
                .addComment("TODO: set fields on the DTO and assert on the created result")
                .build());

        testBuilder.addMethod(MethodSpec.methodBuilder("findByIdReturnsCreated" + entityName)
                .addAnnotation(test)
                .addModifiers(Modifier.PUBLIC)
                .addComment("TODO: implement - create an entity, then verify findById returns it")
                .build());

        writeJavaFile(packageName, testBuilder.build());
        log.info("Generated: " + className);
    }

    private void generateControllerIntegrationTest() throws IOException {
        String className = entityName + "ControllerIntegrationTest";
        String packageName = basePackage + ".controller";

        ClassName springBootTest = ClassName.get("org.springframework.boot.test.context", "SpringBootTest");
        ClassName webEnvironment = ClassName.get("org.springframework.boot.test.context", "SpringBootTest", "WebEnvironment");
        ClassName autoConfigureMockMvc = ClassName.get(
                "org.springframework.boot.test.autoconfigure.web.servlet", "AutoConfigureMockMvc");
        ClassName mockMvc = ClassName.get("org.springframework.test.web.servlet", "MockMvc");
        ClassName autowired = ClassName.get("org.springframework.beans.factory.annotation", "Autowired");
        ClassName test = ClassName.get("org.junit.jupiter.api", "Test");
        ClassName mockMvcRequestBuilders = ClassName.get(
                "org.springframework.test.web.servlet.request", "MockMvcRequestBuilders");
        ClassName status = ClassName.get("org.springframework.test.web.servlet.result", "MockMvcResultMatchers");

        String basePath = "/api/v1/" + decapitalize(entityName) + "s";

        TypeSpec.Builder testBuilder = TypeSpec.classBuilder(className)
                .addJavadoc("Integration test skeleton for $L.\n", entityName + "Controller")
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addAnnotation(AnnotationSpec.builder(springBootTest)
                        .addMember("webEnvironment", "$T.$L", webEnvironment, "RANDOM_PORT")
                        .build())
                .addAnnotation(autoConfigureMockMvc)
                .addField(FieldSpec.builder(mockMvc, "mockMvc", Modifier.PRIVATE)
                        .addAnnotation(autowired)
                        .build());

        testBuilder.addMethod(MethodSpec.methodBuilder("getAllReturnsOk")
                .addAnnotation(test)
                .addModifiers(Modifier.PUBLIC)
                .addException(Exception.class)
                .addStatement("mockMvc.perform($T.get($S))\n    .andExpect($T.status().isOk())",
                        mockMvcRequestBuilders, basePath, status)
                .build());

        testBuilder.addMethod(MethodSpec.methodBuilder("createWithInvalidBodyReturnsBadRequest")
                .addAnnotation(test)
                .addModifiers(Modifier.PUBLIC)
                .addException(Exception.class)
                .addComment("TODO: implement - post an invalid payload and assert 400")
                .build());

        writeJavaFile(packageName, testBuilder.build());
        log.info("Generated: " + className);
    }

    private void writeJavaFile(String packageName, TypeSpec typeSpec) throws IOException {
        JavaFile javaFile = JavaFile.builder(packageName, typeSpec)
                .addFileComment("Generated by Adhar Kit Maven Plugin")
                .indent("    ")
                .build();
        javaFile.writeTo(outputDirectory);
    }

    private String decapitalize(String name) {
        return Character.toLowerCase(name.charAt(0)) + name.substring(1);
    }
}
