package com.adhar.kit.maven.generator;

import com.squareup.javapoet.*;
import org.apache.maven.plugin.logging.Log;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;

/**
 * Generator for Spring Data JPA repository interfaces.
 *
 * <p>Generates repository interfaces extending JpaRepository with
 * common query methods.</p>
 *
 * @author Adhar Platform Team
 * @since 1.0.0
 */
public class RepositoryGenerator {
    private final String basePackage;
    private final String entityName;
    private final File outputDirectory;
    private final Log log;

    public RepositoryGenerator(String basePackage, String entityName, File outputDirectory, Log log) {
        this.basePackage = basePackage;
        this.entityName = entityName;
        this.outputDirectory = outputDirectory;
        this.log = log;
    }

    /**
     * Generates a JPA repository interface with common query methods.
     */
    public void generate() throws IOException {
        log.info("Generating repository for: " + entityName);

        String interfaceName = entityName + "Repository";
        String packageName = basePackage + ".repository";

        ClassName entityType = ClassName.get(basePackage + ".entity", entityName);
        ClassName jpaRepository = ClassName.get(
                "org.springframework.data.jpa.repository", "JpaRepository");
        ClassName jpaSpecificationExecutor = ClassName.get(
                "org.springframework.data.jpa.repository", "JpaSpecificationExecutor");
        ClassName repositoryAnnotation = ClassName.get(
                "org.springframework.stereotype", "Repository");
        ClassName page = ClassName.get("org.springframework.data.domain", "Page");
        ClassName pageable = ClassName.get("org.springframework.data.domain", "Pageable");
        ClassName optional = ClassName.get("java.util", "Optional");
        ClassName list = ClassName.get("java.util", "List");
        ClassName query = ClassName.get("org.springframework.data.jpa.repository", "Query");
        ClassName param = ClassName.get("org.springframework.data.repository.query", "Param");

        TypeSpec repositoryInterface = TypeSpec.interfaceBuilder(interfaceName)
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(repositoryAnnotation)
                .addJavadoc("Repository for $L entity.\n", entityName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                // Extend JpaRepository<Entity, Long>
                .addSuperinterface(ParameterizedTypeName.get(jpaRepository,
                        entityType, ClassName.get(Long.class)))
                // Extend JpaSpecificationExecutor<Entity>
                .addSuperinterface(ParameterizedTypeName.get(jpaSpecificationExecutor, entityType))
                // findByName
                .addMethod(MethodSpec.methodBuilder("findByName")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(String.class, "name")
                        .returns(ParameterizedTypeName.get(optional, entityType))
                        .addJavadoc("Finds a $L by name.\n", entityName.toLowerCase())
                        .addJavadoc("\n@param name the name to search for\n")
                        .addJavadoc("@return an Optional containing the entity if found\n")
                        .build())
                // findByNameContainingIgnoreCase
                .addMethod(MethodSpec.methodBuilder("findByNameContainingIgnoreCase")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(String.class, "name")
                        .addParameter(pageable, "pageable")
                        .returns(ParameterizedTypeName.get(page, entityType))
                        .addJavadoc("Searches for $L by name (case-insensitive, partial match).\n",
                                entityName.toLowerCase() + "s")
                        .addJavadoc("\n@param name the search term\n")
                        .addJavadoc("@param pageable pagination information\n")
                        .addJavadoc("@return page of matching entities\n")
                        .build())
                // existsByName
                .addMethod(MethodSpec.methodBuilder("existsByName")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(String.class, "name")
                        .returns(TypeName.BOOLEAN)
                        .addJavadoc("Checks if a $L exists with the given name.\n",
                                entityName.toLowerCase())
                        .addJavadoc("\n@param name the name to check\n")
                        .addJavadoc("@return true if an entity with the name exists\n")
                        .build())
                // Custom JPQL query example
                .addMethod(MethodSpec.methodBuilder("search")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addAnnotation(AnnotationSpec.builder(query)
                                .addMember("value", "$S",
                                        "SELECT e FROM " + entityName + " e WHERE "
                                                + "LOWER(e.name) LIKE LOWER(CONCAT('%', :keyword, '%'))")
                                .build())
                        .addParameter(ParameterSpec.builder(String.class, "keyword")
                                .addAnnotation(AnnotationSpec.builder(param)
                                        .addMember("value", "$S", "keyword")
                                        .build())
                                .build())
                        .addParameter(pageable, "pageable")
                        .returns(ParameterizedTypeName.get(page, entityType))
                        .addJavadoc("Searches for $L using a keyword.\n",
                                entityName.toLowerCase() + "s")
                        .addJavadoc("\n@param keyword the search keyword\n")
                        .addJavadoc("@param pageable pagination information\n")
                        .addJavadoc("@return page of matching entities\n")
                        .build())
                .build();

        JavaFile javaFile = JavaFile.builder(packageName, repositoryInterface)
                .addFileComment("Generated by Adhar Kit Maven Plugin")
                .indent("    ")
                .build();

        javaFile.writeTo(outputDirectory);
        log.info("Generated repository: " + interfaceName);
    }
}
