package com.adhar.kit.maven.generator;

import com.squareup.javapoet.*;
import org.apache.maven.plugin.logging.Log;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;

/**
 * Generator for Service interfaces and implementations.
 *
 * <p>Generates enterprise-ready service classes with:</p>
 * <ul>
 *   <li>Interface with business methods</li>
 *   <li>Implementation with transaction management</li>
 *   <li>Exception handling</li>
 *   <li>Logging</li>
 *   <li>Metrics annotations</li>
 * </ul>
 *
 * @author Adhar Platform Team
 * @since 1.0.0
 */
public class ServiceGenerator {

    private final String basePackage;
    private final String entityName;
    private final File outputDirectory;
    private final boolean useLombok;
    private final Log log;

    public ServiceGenerator(String basePackage, String entityName, File outputDirectory,
                           boolean useLombok, Log log) {
        this.basePackage = basePackage;
        this.entityName = entityName;
        this.outputDirectory = outputDirectory;
        this.useLombok = useLombok;
        this.log = log;
    }

    /**
     * Generates the service interface and implementation.
     */
    public void generate() throws IOException {
        generateServiceInterface();
        generateServiceImplementation();
        log.info("Generated service for: " + entityName);
    }

    /**
     * Generates the service interface.
     */
    private void generateServiceInterface() throws IOException {
        String interfaceName = entityName + "Service";
        String packageName = basePackage + ".service";

        TypeSpec serviceInterface = TypeSpec.interfaceBuilder(interfaceName)
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Service interface for $L operations.\n", entityName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                // Create method
                .addMethod(MethodSpec.methodBuilder("create")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(ClassName.get(basePackage + ".dto", entityName + "CreateDto"), "dto")
                        .returns(ClassName.get(basePackage + ".dto", entityName + "ResponseDto"))
                        .addJavadoc("Creates a new $L.\n", entityName.toLowerCase())
                        .addJavadoc("\n@param dto the creation data\n")
                        .addJavadoc("@return the created $L\n", entityName.toLowerCase())
                        .build())
                // Update method
                .addMethod(MethodSpec.methodBuilder("update")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(ClassName.get("java.lang", "Long"), "id")
                        .addParameter(ClassName.get(basePackage + ".dto", entityName + "UpdateDto"), "dto")
                        .returns(ClassName.get(basePackage + ".dto", entityName + "ResponseDto"))
                        .addJavadoc("Updates an existing $L.\n", entityName.toLowerCase())
                        .addJavadoc("\n@param id the entity ID\n")
                        .addJavadoc("@param dto the update data\n")
                        .addJavadoc("@return the updated $L\n", entityName.toLowerCase())
                        .build())
                // FindById method
                .addMethod(MethodSpec.methodBuilder("findById")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(ClassName.get("java.lang", "Long"), "id")
                        .returns(ClassName.get(basePackage + ".dto", entityName + "ResponseDto"))
                        .addJavadoc("Finds a $L by ID.\n", entityName.toLowerCase())
                        .addJavadoc("\n@param id the entity ID\n")
                        .addJavadoc("@return the $L\n", entityName.toLowerCase())
                        .build())
                // FindAll method
                .addMethod(MethodSpec.methodBuilder("findAll")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(ClassName.get("org.springframework.data.domain", "Pageable"), "pageable")
                        .returns(ParameterizedTypeName.get(
                                ClassName.get("org.springframework.data.domain", "Page"),
                                ClassName.get(basePackage + ".dto", entityName + "ResponseDto")
                        ))
                        .addJavadoc("Finds all $L with pagination.\n", entityName.toLowerCase() + "s")
                        .addJavadoc("\n@param pageable pagination information\n")
                        .addJavadoc("@return page of $L\n", entityName.toLowerCase() + "s")
                        .build())
                // Delete method
                .addMethod(MethodSpec.methodBuilder("delete")
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(ClassName.get("java.lang", "Long"), "id")
                        .returns(TypeName.VOID)
                        .addJavadoc("Deletes a $L by ID.\n", entityName.toLowerCase())
                        .addJavadoc("\n@param id the entity ID\n")
                        .build())
                .build();

        JavaFile javaFile = JavaFile.builder(packageName, serviceInterface)
                .addFileComment("Generated by Adhar Kit Maven Plugin")
                .indent("    ")
                .build();

        javaFile.writeTo(outputDirectory);
        log.info("Generated interface: " + interfaceName);
    }

    /**
     * Generates the service implementation.
     */
    private void generateServiceImplementation() throws IOException {
        String implName = entityName + "ServiceImpl";
        String interfaceName = entityName + "Service";
        String packageName = basePackage + ".service.impl";

        TypeSpec.Builder serviceImplBuilder = TypeSpec.classBuilder(implName)
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(ClassName.get(basePackage + ".service", interfaceName))
                .addJavadoc("Implementation of $L.\n", interfaceName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addAnnotation(ClassName.get("org.springframework.stereotype", "Service"))
                .addAnnotation(ClassName.get("org.springframework.transaction.annotation", "Transactional"));

        if (useLombok) {
            serviceImplBuilder
                    .addAnnotation(ClassName.get("lombok.extern.slf4j", "Slf4j"))
                    .addAnnotation(ClassName.get("lombok", "RequiredArgsConstructor"));
        }

        // Add repository field
        serviceImplBuilder.addField(
                FieldSpec.builder(
                        ClassName.get(basePackage + ".repository", entityName + "Repository"),
                        decapitalize(entityName) + "Repository",
                        Modifier.PRIVATE, Modifier.FINAL
                ).build()
        );

        // Implement create method
        serviceImplBuilder.addMethod(
                MethodSpec.methodBuilder("create")
                        .addModifiers(Modifier.PUBLIC)
                        .addAnnotation(Override.class)
                        .addParameter(ClassName.get(basePackage + ".dto", entityName + "CreateDto"), "dto")
                        .returns(ClassName.get(basePackage + ".dto", entityName + "ResponseDto"))
                        .addStatement("$L entity = mapToEntity(dto)", entityName)
                        .addStatement("entity = $NRepository.save(entity)", decapitalize(entityName))
                        .addStatement("return mapToDto(entity)")
                        .build()
        );

        // Implement other methods...
        serviceImplBuilder.addMethod(
                MethodSpec.methodBuilder("findById")
                        .addModifiers(Modifier.PUBLIC)
                        .addAnnotation(Override.class)
                        .addAnnotation(ClassName.get("org.springframework.transaction.annotation", "Transactional"))
                        .addParameter(ClassName.get("java.lang", "Long"), "id")
                        .returns(ClassName.get(basePackage + ".dto", entityName + "ResponseDto"))
                        .addStatement("$L entity = $NRepository.findById(id)\n    .orElseThrow(() -> new $T($S + id))",
                                entityName,
                                decapitalize(entityName),
                                ClassName.get("com.adhar.kit.commons.exception", "ResourceNotFoundException"),
                                entityName + " not found with id: ")
                        .addStatement("return mapToDto(entity)")
                        .build()
        );

        TypeSpec serviceImpl = serviceImplBuilder.build();

        JavaFile javaFile = JavaFile.builder(packageName, serviceImpl)
                .addFileComment("Generated by Adhar Kit Maven Plugin")
                .indent("    ")
                .build();

        javaFile.writeTo(outputDirectory);
        log.info("Generated implementation: " + implName);
    }

    private String decapitalize(String name) {
        return Character.toLowerCase(name.charAt(0)) + name.substring(1);
    }
}

