package com.adhar.kit.maven.generator;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import org.apache.maven.plugin.logging.Log;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates a runnable Spring Boot microservice skeleton that builds on
 * {@code adhar-kit-starter}.
 *
 * <p>The generated project follows the standard Maven layout and contains:</p>
 * <ul>
 *   <li>a {@code pom.xml} inheriting from {@code adhar-kit-parent} and depending
 *   on {@code adhar-kit-starter};</li>
 *   <li>a {@code @SpringBootApplication} main class;</li>
 *   <li>an {@code application.yml};</li>
 *   <li>a sample REST controller and service, plus a service unit test.</li>
 * </ul>
 *
 * <p>Java sources are produced with JavaPoet (matching the other generators);
 * the {@code pom.xml} and {@code application.yml} are written as plain text.</p>
 *
 * @author Adhar Platform Team
 * @since 1.0.0
 */
public class ServiceScaffoldGenerator {

    private static final String ADHAR_VERSION = "0.1.0-SNAPSHOT";

    private final String basePackage;
    private final String serviceName;
    private final String artifactId;
    private final File outputDirectory;
    private final Log log;

    public ServiceScaffoldGenerator(String basePackage, String serviceName, String artifactId,
                                    File outputDirectory, Log log) {
        this.basePackage = basePackage;
        this.serviceName = serviceName;
        this.artifactId = artifactId;
        this.outputDirectory = outputDirectory;
        this.log = log;
    }

    /**
     * Generates the full service skeleton under the output directory.
     */
    public void generate() throws IOException {
        log.info("Scaffolding microservice: " + serviceName);

        File mainJava = new File(outputDirectory, "src/main/java");
        File testJava = new File(outputDirectory, "src/test/java");
        File resources = new File(outputDirectory, "src/main/resources");
        mainJava.mkdirs();
        testJava.mkdirs();
        resources.mkdirs();

        writePom();
        writeApplicationYml(resources);
        writeApplicationClass(mainJava);
        writeController(mainJava);
        writeService(mainJava);
        writeServiceTest(testJava);

        log.info("Microservice skeleton generated at: " + outputDirectory);
    }

    private void writePom() throws IOException {
        String pom = ""
                + "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n"
                + "         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
                + "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 "
                + "http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n"
                + "    <modelVersion>4.0.0</modelVersion>\n\n"
                + "    <parent>\n"
                + "        <groupId>com.adhar.kit</groupId>\n"
                + "        <artifactId>adhar-kit-parent</artifactId>\n"
                + "        <version>" + ADHAR_VERSION + "</version>\n"
                + "    </parent>\n\n"
                + "    <groupId>" + basePackage + "</groupId>\n"
                + "    <artifactId>" + artifactId + "</artifactId>\n"
                + "    <version>0.0.1-SNAPSHOT</version>\n"
                + "    <name>" + serviceName + "</name>\n"
                + "    <description>Microservice generated by the Adhar Kit Maven Plugin</description>\n\n"
                + "    <dependencies>\n"
                + "        <dependency>\n"
                + "            <groupId>com.adhar.kit</groupId>\n"
                + "            <artifactId>adhar-kit-starter</artifactId>\n"
                + "            <version>" + ADHAR_VERSION + "</version>\n"
                + "        </dependency>\n"
                + "        <dependency>\n"
                + "            <groupId>org.springframework.boot</groupId>\n"
                + "            <artifactId>spring-boot-starter-test</artifactId>\n"
                + "            <scope>test</scope>\n"
                + "        </dependency>\n"
                + "    </dependencies>\n"
                + "</project>\n";
        writeText(outputDirectory.toPath().resolve("pom.xml"), pom);
        log.info("Generated: pom.xml");
    }

    private void writeApplicationYml(File resources) throws IOException {
        String yml = ""
                + "spring:\n"
                + "  application:\n"
                + "    name: " + artifactId + "\n\n"
                + "server:\n"
                + "  port: 8080\n\n"
                + "management:\n"
                + "  endpoints:\n"
                + "    web:\n"
                + "      exposure:\n"
                + "        include: health,info\n";
        writeText(resources.toPath().resolve("application.yml"), yml);
        log.info("Generated: application.yml");
    }

    private void writeApplicationClass(File mainJava) throws IOException {
        TypeSpec application = TypeSpec.classBuilder(serviceName + "Application")
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Entry point for the $L microservice.\n", serviceName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addAnnotation(ClassName.get(
                        "org.springframework.boot.autoconfigure", "SpringBootApplication"))
                .addMethod(MethodSpec.methodBuilder("main")
                        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                        .addParameter(String[].class, "args")
                        .addStatement("$T.run($L.class, args)",
                                ClassName.get("org.springframework.boot", "SpringApplication"),
                                serviceName + "Application")
                        .build())
                .build();
        writeJava(mainJava, basePackage, application);
        log.info("Generated: " + serviceName + "Application");
    }

    private void writeController(File mainJava) throws IOException {
        ClassName serviceType = ClassName.get(basePackage + ".service", "SampleService");
        ClassName responseEntity = ClassName.get("org.springframework.http", "ResponseEntity");
        ClassName stringType = ClassName.get("java.lang", "String");

        TypeSpec controller = TypeSpec.classBuilder("SampleController")
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Sample REST controller for the $L microservice.\n", serviceName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RestController"))
                .addAnnotation(AnnotationSpec.builder(
                                ClassName.get("org.springframework.web.bind.annotation", "RequestMapping"))
                        .addMember("value", "$S", "/api/v1/sample")
                        .build())
                .addAnnotation(ClassName.get("lombok", "RequiredArgsConstructor"))
                .addField(FieldSpec.builder(serviceType, "sampleService",
                        Modifier.PRIVATE, Modifier.FINAL).build())
                .addMethod(MethodSpec.methodBuilder("greeting")
                        .addModifiers(Modifier.PUBLIC)
                        .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "GetMapping"))
                        .returns(ParameterizedTypeName.get(responseEntity, stringType))
                        .addStatement("return $T.ok(sampleService.greeting())", responseEntity)
                        .build())
                .build();
        writeJava(mainJava, basePackage + ".controller", controller);
        log.info("Generated: SampleController");
    }

    private void writeService(File mainJava) throws IOException {
        TypeSpec service = TypeSpec.classBuilder("SampleService")
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Sample service for the $L microservice.\n", serviceName)
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addAnnotation(ClassName.get("org.springframework.stereotype", "Service"))
                .addMethod(MethodSpec.methodBuilder("greeting")
                        .addModifiers(Modifier.PUBLIC)
                        .returns(String.class)
                        .addStatement("return $S", "Hello from " + serviceName)
                        .build())
                .build();
        writeJava(mainJava, basePackage + ".service", service);
        log.info("Generated: SampleService");
    }

    private void writeServiceTest(File testJava) throws IOException {
        ClassName test = ClassName.get("org.junit.jupiter.api", "Test");
        ClassName assertions = ClassName.get("org.assertj.core.api", "Assertions");
        ClassName serviceType = ClassName.get(basePackage + ".service", "SampleService");

        TypeSpec serviceTest = TypeSpec.classBuilder("SampleServiceTest")
                .addJavadoc("Unit test for $L.\n", "SampleService")
                .addJavadoc("\n@author Generated by Adhar Kit Maven Plugin\n")
                .addJavadoc("@since 1.0.0\n")
                .addMethod(MethodSpec.methodBuilder("greetingReturnsMessage")
                        .addAnnotation(test)
                        .addModifiers(Modifier.PUBLIC)
                        .addStatement("$T service = new $T()", serviceType, serviceType)
                        .addStatement("$T.assertThat(service.greeting()).contains($S)",
                                assertions, serviceName)
                        .build())
                .build();
        writeJava(testJava, basePackage + ".service", serviceTest);
        log.info("Generated: SampleServiceTest");
    }

    private void writeJava(File sourceRoot, String packageName, TypeSpec typeSpec) throws IOException {
        JavaFile javaFile = JavaFile.builder(packageName, typeSpec)
                .addFileComment("Generated by Adhar Kit Maven Plugin")
                .indent("    ")
                .build();
        javaFile.writeTo(sourceRoot);
    }

    private void writeText(Path path, String content) throws IOException {
        Files.createDirectories(path.getParent());
        Files.writeString(path, content, StandardCharsets.UTF_8);
    }
}
